#!/usr/bin/env python3
"""Rushing Beat Shura: The Eternal Conflict — English patch installer.

Applies the bundled IPS patch to an UNHEADERED Japanese "Rushing Beat Shura"
(Super Famicom) ROM and writes the English-patched ROM next to it.

Ways to run it:
  * Double-click the Windows .exe   → a dialog asks you to pick your ROM.
  * Drag a ROM file onto the .exe (or this .py).
  * Terminal:  python apply_patch.py [path/to/rom.sfc]
               apply_patch.exe [path\\to\\rom.sfc]

The original ROM is identified by its SHA-256, so the patch can never be applied
to the wrong file. The patch stores only the *differences* between the Japanese
and English ROMs — it contains no copyrighted ROM data, which is why it can be
distributed freely. You must supply your own legally-obtained Japanese ROM.

NOTE: this file is GENERATED by tools/make_patcher.py from
tools/apply_patch_template.py — do not edit it by hand.
"""
from __future__ import annotations

import base64
import gzip
import hashlib
import sys
from pathlib import Path

# ---- embedded patch + identity (injected by make_patcher.py) --------------
TITLE          = "@@TITLE@@"
VERSION        = "@@VERSION@@"
ORIG_SHA256    = "@@ORIG_SHA256@@"
ORIG_SIZE      = @@ORIG_SIZE@@
PATCHED_SHA256 = "@@PATCHED_SHA256@@"
PATCHED_SIZE   = @@PATCHED_SIZE@@
OUTPUT_NAME    = "@@OUTPUT_NAME@@"          # written next to the input ROM
_PATCH_GZ_B64  = "@@PATCH_GZ_B64@@"

HEADER_SIZE = 512   # SMC/copier header — auto-stripped if present


class PatchError(Exception):
    """A user-facing problem (wrong ROM, write failure, …)."""


def _embedded_patch() -> bytes:
    return gzip.decompress(base64.b64decode(_PATCH_GZ_B64))


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def apply_ips(patch: bytes, src: bytes) -> bytes:
    """Apply a standard IPS patch (with RLE records) to `src`. The output file
    is grown as needed so a 2 MB source can expand to the 4 MB patched ROM."""
    if patch[:5] != b"PATCH":
        raise PatchError("Embedded patch is corrupt (missing IPS 'PATCH' header).")
    out = bytearray(src)
    i, n = 5, len(patch)
    while i < n:
        if patch[i:i + 3] == b"EOF":
            break
        offset = int.from_bytes(patch[i:i + 3], "big"); i += 3
        length = int.from_bytes(patch[i:i + 2], "big"); i += 2
        if length == 0:                          # RLE record
            run = int.from_bytes(patch[i:i + 2], "big"); i += 2
            chunk = bytes([patch[i]]) * run;       i += 1
        else:
            chunk = patch[i:i + length];           i += length
        end = offset + len(chunk)
        if end > len(out):
            out.extend(b"\x00" * (end - len(out)))
        out[offset:end] = chunk
    return bytes(out)


def patch_rom(in_path: Path) -> tuple[Path, str]:
    """Verify, patch, and write. Returns (output_path, note). Raises PatchError."""
    try:
        data = in_path.read_bytes()
    except OSError as e:
        raise PatchError(f"Could not read the ROM:\n{in_path}\n\n{e}") from e

    note = ""
    # Auto-strip a 512-byte copier header (common on .smc dumps).
    if len(data) == ORIG_SIZE + HEADER_SIZE and (len(data) - HEADER_SIZE) % 1024 == 0:
        data = data[HEADER_SIZE:]
        note = "Stripped a 512-byte copier header.\n"

    got = _sha256(data)
    if got != ORIG_SHA256:
        if got == PATCHED_SHA256:
            raise PatchError("This ROM is already patched to English — nothing to do.")
        raise PatchError(
            "That file isn't the expected original ROM.\n\n"
            f"Expected: unheadered Rushing Beat Shura (Japan), {ORIG_SIZE:,} bytes\n"
            f"  sha256  {ORIG_SHA256}\n"
            f"Got:      {len(data):,} bytes\n"
            f"  sha256  {got}\n\n"
            "Use an unmodified Japanese ROM (not already patched, not a different "
            "dump or region)."
        )

    patched = apply_ips(_embedded_patch(), data)
    if _sha256(patched) != PATCHED_SHA256:
        raise PatchError("Internal error: the patched ROM failed its checksum verification.")

    out_path = in_path.with_name(OUTPUT_NAME)
    try:
        out_path.write_bytes(patched)
    except OSError as e:
        raise PatchError(f"Could not write the patched ROM:\n{out_path}\n\n{e}") from e
    return out_path, note


# ---- UI: dialogs when there's no console, plain text when there is --------

def _gui_available() -> bool:
    try:
        import tkinter  # noqa: F401
        return True
    except Exception:
        return False


def _pick_rom_gui() -> Path | None:
    import tkinter as tk
    from tkinter import filedialog
    root = tk.Tk()
    root.withdraw()
    path = filedialog.askopenfilename(
        title=f"{TITLE} — select your Japanese ROM",
        filetypes=[("SNES/SFC ROM", "*.sfc *.smc *.fig *.swc"), ("All files", "*.*")],
    )
    root.destroy()
    return Path(path) if path else None


def _message_gui(title: str, message: str, error: bool = False) -> None:
    import tkinter as tk
    from tkinter import messagebox
    root = tk.Tk()
    root.withdraw()
    (messagebox.showerror if error else messagebox.showinfo)(title, message)
    root.destroy()


def main(argv: list[str]) -> int:
    # GUI mode: a frozen .exe (no console) or launched with no ROM argument.
    use_gui = getattr(sys, "frozen", False) or len(argv) < 2
    has_gui = _gui_available()

    if len(argv) >= 2:
        in_path = Path(argv[1]).expanduser()
    elif has_gui:
        picked = _pick_rom_gui()
        if not picked:
            return 0  # user cancelled
        in_path = picked
    else:
        print(f"usage: {Path(argv[0]).name} <path-to-japanese-rom.sfc>", file=sys.stderr)
        return 2

    try:
        out_path, note = patch_rom(in_path)
    except PatchError as e:
        msg = str(e)
        if use_gui and has_gui:
            _message_gui(f"{TITLE} — could not patch", msg, error=True)
        else:
            print(f"\nERROR: {msg}", file=sys.stderr)
        return 1

    ok = (f"{note}\nSuccess! English ROM written to:\n{out_path}\n\n"
          f"{TITLE} {VERSION}").strip()
    if use_gui and has_gui:
        _message_gui(f"{TITLE} — done", ok)
    else:
        print(f"\n{ok}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
