#!/usr/bin/env python3
"""Convert data/{lang}/narration.txt (human-readable translation) into the
retrotool SCRIPT-section source data/{lang}/narration_screens.txt.

The post-intro-scroll character-narration screens are pointer-handled text
blocks in the $1F:C57F table (idx 1-19), rendered half-width / render-at-once by
patches/narration_render.asm. tables/narration.toml is a kind="script" pointer
DataDef over those 19 slots. retrotool's script source format is:

    <<$PTRBASE:SRCIDX[$ENTRYADDR]>>          (decimal FILE offsets)
    [lo][hi]<half-width text via rbshura_en.tbl>

where the leading [lo][hi] hex tokens are the entry's 2-byte VRAM dest word (LE)
that the renderer loads into $2116. The $FF terminator is appended by the
encoder (do NOT include it here — extractor/encoder inverse invariant).

The 19 slots (src idx 0-18 = table idx 1-19) share pointers where a screen
persists across cutscene steps; the structure + original entry addresses below
mirror exactly what `retrotool extract --only narration_screens` produces, so
shared slots dedup to one packed block on build.

Usage: python tools/gen_narration_source.py        (writes en + jp)
"""
from __future__ import annotations
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PTR_BASE_DEC = 0x1FC581          # pointers.offset (file) = decimal header base

# VRAM-dest delta between consecutive on-screen text lines. Each half-width
# glyph is 8x16 = 2 stacked tiles, so a line occupies 2 tilemap rows; one row =
# $100 VRAM words, so a line is $200. Tune if vertical line spacing looks off.
LINE_STRIDE = 0x200

# src idx (0-18) -> (group key, original entry file-offset decimal).
# group keys index the parsed screens; shared slots repeat the key+addr.
SLOTS = [
    ("elfin_name", 0x1FC5D9), ("elfin_name", 0x1FC5D9), ("elfin_name", 0x1FC5D9),
    ("elfin_epi",  0x1FC5E7),
    ("dick_name",  0x1FC65D), ("dick_name",  0x1FC65D),
    ("dick_epi",   0x1FC669),
    ("kyth_name",  0x1FC6D5), ("kyth_name",  0x1FC6D5),
    ("kyth_epi1",  0x1FC6E9),
    ("kyth_epi2",  0x1FC75F),
    ("jimmy_name", 0x1FC7DB), ("jimmy_name", 0x1FC7DB),
    ("jimmy_epi1", 0x1FC7E9), ("jimmy_epi1", 0x1FC7E9),
    ("jimmy_epi2", 0x1FC883), ("jimmy_epi2", 0x1FC883),
    ("jimmy_epi2", 0x1FC883), ("jimmy_epi2", 0x1FC883),
]
# 10 unique groups, in screen order, paired with the parsed translation:
GROUP_ORDER = ["elfin_name", "elfin_epi", "dick_name", "dick_epi",
               "kyth_name", "kyth_epi1", "kyth_epi2",
               "jimmy_name", "jimmy_epi1", "jimmy_epi2"]


def read_utf(p: Path) -> str:
    raw = p.read_bytes()
    return raw.decode("utf-16" if raw[:2] == b"\xff\xfe" else "utf-8")


def parse_translation(path: Path):
    """Returns list of (dest, [lines]) in screen order (10 screens). Each
    source line under a <<...>> header becomes one on-screen line."""
    text = read_utf(path)
    screens, dest, lines = [], None, []
    for line in text.split("\n"):
        m = re.match(r"<<idx=[\d-]+ ptr=\$[0-9A-Fa-f]+ dest=\$([0-9A-Fa-f]+)", line)
        if m:
            if dest is not None:
                screens.append((dest, lines))
            dest, lines = int(m.group(1), 16), []
        elif line.startswith(";"):
            continue
        elif dest is not None and line.strip():
            lines.append(line.strip())
    if dest is not None:
        screens.append((dest, lines))
    return screens


def build_body(dest: int, lines: list[str]) -> str:
    """[destLE]line0 [FE][dest+STRIDE]line1 [FE][dest+2*STRIDE]line2 ...
    The leading dest is consumed by the renderer at entry; each later line is
    repositioned via the $FE control so source line breaks = screen rows."""
    parts = []
    for n, ln in enumerate(lines):
        d = (dest + n * LINE_STRIDE) & 0xFFFF
        lo, hi = d & 0xFF, (d >> 8) & 0xFF
        parts.append(("" if n == 0 else "[FE]") + f"[{lo:02X}][{hi:02X}]{ln}")
    return "".join(parts)


def gen_lang(lang: str) -> int:
    # Always source the ENGLISH translation: the half-width PK (Latin) renderer
    # can't render the original kana, and only the EN ROM ships, so the JP
    # source carries the same English (the build needs both files to exist).
    src = ROOT / "data/en/narration.txt"
    if not src.exists():
        print(f"  skip {lang}: data/en/narration.txt not found")
        return 0
    screens = parse_translation(src)
    if len(screens) != len(GROUP_ORDER):
        sys.exit(f"{lang}: parsed {len(screens)} screens, expected {len(GROUP_ORDER)}")
    by_group = {g: s for g, s in zip(GROUP_ORDER, screens)}

    out = [
        "; Auto-generated by tools/gen_narration_source.py — retrotool script",
        "; source for the $1F:C57F idx-1-19 narration pointer blocks.",
        "; Body = [destLE]line0 then [FE][destLE]lineN per line (source line",
        "; breaks = screen rows); encoder appends the $FF terminator.",
        f"; LANG={lang}",
    ]
    for i, (group, addr) in enumerate(SLOTS):
        dest, lines = by_group[group]
        out.append(f"<<${PTR_BASE_DEC}:{i}[${addr}]>>")
        out.append(build_body(dest, lines))
    blob = ("\n".join(out) + "\n").encode("utf-16-le")
    (ROOT / f"data/{lang}/narration_screens.txt").write_bytes(b"\xff\xfe" + blob)
    print(f"wrote data/{lang}/narration_screens.txt ({len(SLOTS)} slots, "
          f"{len(set(g for g, _ in SLOTS))} unique)")
    return len(SLOTS)


def main() -> None:
    # Only EN is generated. The build encodes from en_data_dir (data/en), so the
    # EN source drives the shipped ROM. data/jp/narration_screens.txt is the
    # AUTHENTIC ROM extraction (`retrotool extract --only narration_screens
    # --lang jp`) — do NOT clobber it with English here. (Those screens are
    # glyph-DMA descriptors, so the JP dump is glyph-index tokens, not readable
    # text; the readable JP lives in data/jp/narration.txt.)
    gen_lang("en")


if __name__ == "__main__":
    main()
